# Site settings
site: Dan Breu
title: Dan Breu
keywords: danbreu, blog, personal, technology, building, software, design, enterpreneurship
description: >-
  Personal Website of Dan Breu, a blog about technology, building software, design and enterpreneurship.
lang: en-US
timezone:  America/Vancouver
repo:  # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Danilo Briceño
  bio: Innovator <br> Founder @ekiscyber <br> AppSec / DevSec
  picture: assets/images/danbreu.com.png
  github: dan-breu # github username
  twitter: dan_breu # twitter username
  facebook: dan_breu # facebook username
  instagram: dan_breu # instagram username
  youtube: https://www.youtube.com/@danbreu # youtube username
  linkedin: danbreu # linkedin username
  email: danbreu.com@gmail.com # email adress


# URL settings
url: danbreu.com # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false